apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-plil
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-plil
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-plil
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-plil
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-plil
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zmzh-tenant/nodejs-users/simple-nodejs-app-plil@sha256:486f02cbfd5835fb84e5b2410b4a60316c2c21540a5b832f18a1d1ae5421f8d5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
